DROP TABLE IF EXISTS DOG;

CREATE TABLE DOG
(
   DOG_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   DOG_NAME VARCHAR(255) NOT NULL,
   DOG_IMAGE MEDIUMBLOB NOT NULL,
   DOG_BREED_ID VARCHAR(255) NOT NULL,
);

CREATE TABLE BREED
(
   BREED_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   BREED_NAME VARCHAR(255) NOT NULL,
);